Chm 270 move countries-thesaurus- realm configuration api service
scbd/scbd-common pull request #14
Opened 2024-02-13 02:16 UTC by liyuanmontreal

Move countries/thesaurus/realm-configuration api service from ORT to scbd-common.
Add functions in api-base.js
add unit test for every file.

how to test:
1. install vitest :" npm install -D vitest"
2. add vitest extension in VSCode
3. use "npx vitest run" in vitest command line,  or use test window, or use "test" script to run unit testing.

2024-02-14 18:46 UTC, blaisefonseca commented on src/services/api/api-base.js
> +export function toUrlParam(value) {
can you call it sanitizeUrlParam,

2024-02-14 18:48 UTC, blaisefonseca commented on src/services/api/thesaurus.js
> +    return this.http.get(`/api/v2013/thesaurus/domains/`)
```suggestion
    return this.http.get(`/api/v2013/thesaurus/domains`)
```

2024-02-14 18:50 UTC, blaisefonseca commented on src/services/api/thesaurus.js
> +  async getDomain(identifier, { relations } = {})  {
there is no relation params for domain api

2024-02-16 03:12 UTC, liyuanmontreal commented on src/services/api/api-base.js
> +export function toUrlParam(value) {
done

2024-02-16 03:12 UTC, liyuanmontreal commented on src/services/api/thesaurus.js
> +    return this.http.get(`/api/v2013/thesaurus/domains/`)
done

2024-02-16 03:13 UTC, liyuanmontreal commented on src/services/api/thesaurus.js
> +  async getDomain(identifier, { relations } = {})  {
done

2024-02-19 14:50 UTC, sbilodeau requested changes

2024-02-19 14:50 UTC, sbilodeau commented on src/services/api/api-base.js
> +// if(/\localhost$/i   .test(window?.location?.hostname || '')) sitePrefixUrl= '/';
his was a temp fix for you computer. please uncommit this

2024-02-19 14:50 UTC, sbilodeau commented on src/services/api/api-base.js
> +  return value;
I think this can be simplied to this:

```suggestion
  if(value!==undefined) value = JSON.stringify(value);
  return value; 
```

2024-02-19 14:50 UTC, sbilodeau commented on src/services/api/api-base.js
> +export function mapObjectId(id){
maybe we can offload these s functions (mapObjectId, isObjectId) + castinh to `{$oid} to a class... this is to be dicussed
EG:
```javascript
        class ObjectId {
            #id
            constructor(id) {
                this.#id = id;
            }

            get _id() {
              return this.#id;
            }

            isObjectId(id) {
               ... 
            }

            toObjectId(id) {
               ... 
            }

            toString() {
              return this._id;
            }

            toJSON() {
              return JSON.stringify({ $oid: this._id }, null, '');
            }
        
        }
```

2024-02-19 14:50 UTC, sbilodeau commented on src/services/api/realm-configuration.js
> +  async getRealmConfigurationByHost(host)  {
if `host` is optional maybe it should be passed using `{ host }`
```suggestion
  async getRealmConfigurationByHost({ host }={})  {
```

2024-02-19 14:50 UTC, sbilodeau commented on src/services/api/realm-configuration.js
> +      host = window.location.host || useRuntimeConfig().public.REALM_CONF_HOST
not sure `useRuntimeConfig` exists

2024-02-19 14:50 UTC, sbilodeau commented on src/services/api/api-base.js
> +  return ![undefined, null].includes(params);
I'm not sure about this function... or it nameing. I would say that `null` can be a very valid value. In on another hand, is an empty string `""` would be valid or not? if you need a `code` to be added to your url path and and you pass `code:""` then the value is invalid!

Maybe should be we should use similar implementa a C# `string.isNullOrWhiteSpace()`

to be dicussed

2024-02-19 14:50 UTC, sbilodeau commented on src/services/api/countries.js
> +    if(!isValid(code)) throw Error(`invalid value for code`);
base ont the current `isValid()` implementation, `""` will be consirered valid but... it is not

2024-02-19 14:50 UTC, sbilodeau commented on test/services/api/api-base.test.js
> +})
base ont the current isValid() implementation, "" will be consirered valid but...

2024-02-19 14:50 UTC, sbilodeau commented on test/services/api/countries.test.js
> +        "__v":      expect.any(Number),
drop
```suggestion
```

2024-02-19 14:50 UTC, sbilodeau commented on test/services/api/countries.test.js
> +        "__v":      expect.any(Number),
drop
```suggestion
```

2024-02-19 14:50 UTC, sbilodeau commented on test/services/api/countries.test.js
> +        "__v":      expect.any(Number),
drop
```suggestion
```

2024-02-19 14:50 UTC, sbilodeau commented on vite.config.js
>  import vue2 from '@vitejs/plugin-vue2'
not supposed to be vue3?

2024-02-20 20:41 UTC, liyuanmontreal commented on src/services/api/api-base.js
> +  return value;
if value is number or string ,  use JSON.stringify(value) will cause error.

2024-02-21 19:01 UTC, blaisefonseca commented on src/services/api/api-base.js
> +export function mapObjectId(id){
we should do this in a seperate PR

2024-02-21 19:02 UTC, blaisefonseca commented on src/services/api/api-base.js
> +  return ![undefined, null].includes(params);
@liyuanmontreal  we should do this in a separate PR

2024-02-21 20:46 UTC, merged